### ISSUE TITLE
input / output flow not correct

### ISSUE THREAD

**Issue by mastercrop** [xtreamui/XtreamUI#13]
input / output flow is not correct in the dashboard

**Comment by gtaman92** [comment]
Can you do me a favour and elaborate a little on this. Would be great if you could get the actual input and outflow and reported input and outflow, so I can see how far out they are. I take it direct from the database so the info is provided by Xtream Codes, but there must be an issue somewhere

**Comment by mastercrop** [comment]
Please check this [screenshot](https://we.tl/t-3HzD5hhGj6) using iftop at the same time on the same LB, you will see the difference.

It seems that "bytes_sent":,"bytes_received": in xtream DB are Mbps, it may be where the issue is coming from :)
