### ISSUE TITLE
Extend expired user issue

### ISSUE THREAD

**Issue by azsenca** [xtreamui/XtreamUI#170]
There is a issue with extending expired users. In UI it writes normal date, +30 days from today, but in database it extends it from date it expired, +30 days.

![ress1](https://user-images.githubusercontent.com/1789117/67118584-72f56380-f1e5-11e9-9bdd-92a9e3bbe709.PNG)
![ress2](https://user-images.githubusercontent.com/1789117/67118591-75f05400-f1e5-11e9-88e0-cedc2ad65d4f.PNG)
![ress3](https://user-images.githubusercontent.com/1789117/67118597-7983db00-f1e5-11e9-9ec2-b81cb24d7f47.PNG)

**Comment by jackchoui** [comment]
With latest update this is not an issue, pleas close

**Comment by azsenca** [comment]
It works now as it should.
