### ISSUE TITLE
M3U not working

### ISSUE THREAD

**Issue by Hydrateammaster** [xtreamui/XtreamUI#33]
When trying to pull an m3u from a line its a blank page 
Error log show:
2019/10/07 16:47:22 [error] 5445#5445: *1706980 recv() failed (104: Connection reset by peer) while reading upstream, client: XXX, server: , request: "GET /oasispat1/9TwZ5Hd8hl/554 HTTP/1.1", upstream: "fastcgi://unix:/home/xtreamcodes/iptv_xtream_codes/php/VaiIb8.sock:", host: "XXX

XXX= server/client IP

**Comment by mytvpro** [comment]
Are you using properly configured streaming port? Steps to reproduce this issue?

**Comment by Hydrateammaster** [comment]
please disregard old xc database was the issue
