### ISSUE TITLE
error while loading shared libraries: libexslt.so.0

### ISSUE THREAD

**Issue by zaedynoaklan** [xtreamui/XtreamUI#34]
Setup went fine on VPS A but on VPS B I get an error:
https://i.gyazo.com/b595656ca404c1eb1aa9d5ea26729aa9.png
Both Ubuntu 18.04

And not really complete, a blank nginx page appears after.

sudo apt-get update did not help.

The error in every setup: MAIN, LB, ADMIN

What it could be?

**Comment by shinctl** [comment]
this should not be here... if ure a IPTV provider u should have minimum knowledge lol.
 apt-get install libxslt1-dev libcurl3 libgeoip-dev python

**Comment by mytvpro** [comment]
right even if you don't know if you get an error about something missing google how to get it

**Comment by zaedynoaklan** [comment]
> this should not be here... if ure a IPTV provider u should have minimum knowledge lol.
> apt-get install libxslt1-dev libcurl3 libgeoip-dev python

sorry, I didn't know where to ask.
Thanks, the command solved the problem. It may help later for more people
