### ISSUE TITLE
server restarts then the panel will not work

### ISSUE THREAD

**Issue by maxytech** [xtreamui/XtreamUI#44]
server restarts then the panel will not work

**Comment by mytvpro** [comment]
Steps to recreate this issue?

**Comment by Dalocom** [comment]
That.s because you must start_service at boottime
/home/xtreamcodes/iptv_xtream_codes/start_services.sh

**Comment by maxytech** [comment]
admin panel re-established and everything worked  no data loss

**Comment by mytvpro** [comment]
yes xc services should auto start on boot this needs to be added to cron or system.d or something
