### ISSUE TITLE
Streams not starting

### ISSUE THREAD

**Issue by DatCrazyDelphox** [xtreamui/XtreamUI#98]
The only thing it says is that an error occurred when processing request

**Comment by mywebiptv** [comment]
I HAD EXACTLY SAME PROBLEME

**Comment by mywebiptv** [comment]
only on-demand work

**Comment by mywebiptv** [comment]
An error occured while processing your request.

**Comment by DatCrazyDelphox** [comment]
figured what happened.
You cannot change the server http port, as it makes the streams unplayable
now lets wait for a proper fix for this
